let EMPTY_PLACEHOLDERS: [String] = [
  "Blank page who??",
  "Cook something wild 🍳",
  "Your brain called 🧠",
  "Draw... anything? 👀",
  "Feeling artsy or what?",
  "Prove you exist ✍️",
  "Create. Or don't. 😏",
  "Make a mess 🎨",
  "Surprise yourself 💥",
  "Draw your nonsense 💫",
  "Anything fun today?",
  "Unleash the scribble 🌀",
  "Start the chaos 😈",
  "No Joodles? Tragic.",
  "Draw before thinking 🤪",
  "One line = therapy",
  "Your canvas is lonely 🥺",
  "Scribble responsibly 🚫",
  "Manifest vibes only 🌈",
  "Brain dump zone 💭",
  "Go feral with it 🐾",
]
